# ///////////////////////////BASIC SETTINGS///////////////////////
# Enable colors and change prompt:
autoload -U colors && colors

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

# Basic auto/tab complete:
fpath+=~/.config/zsh/zfunc
autoload -U bashcompinit
bashcompinit
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M viins 'kj' vi-cmd-mode
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M vicmd 'jj' history-substring-search-up
bindkey -M vicmd 'kk' history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey -v '^?' backward-delete-char

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

#//////////////////////////EXPORTS///////////////////////////////
export EDITOR=nvim
export PATH="$PATH":"$HOME/local/flutter/bin/"
export PATH="$PATH":"$HOME/local/tools/bin/"
export PATH="$PATH":"$HOME/.local/bin/"
export PATH="/usr/local/sbin:$PATH";
export PATH="$HOME/local/.blogger_cli/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$HOME/.emacs.d/bin:$PATH"

# Export the Android SDK path 
export ANDROID_HOME=$HOME/local/android-sdk
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Fixes sdkmanager error with java versions higher than java 8 !!MAY cause problems otherwise
#export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'

# export pyenv
if [ -d ~/.pyenv/bin ]; then
  export PATH="~/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
  export PYENV_ROOT='~/.pyenv/'
fi

export XDG_CONFIG_HOME="$HOME/.config/"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/ptpython/.pythonrc.py"

# init fasd
eval "$(fasd --init auto)"
export MANPATH="/usr/local/man:$MANPATH"


if [ -d ~/.nvm ]; then
source /usr/share/nvm/init-nvm.sh
fi

eval "$(register-python-argcomplete pipx)"

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
