#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
README_PATH="$ROOT_DIR/README.md"

GENERATOR_NAME="generate-readme.sh"
export ROOT_DIR README_PATH GENERATOR_NAME

python3 - <<'PY'
import os
from pathlib import Path

root = Path(os.environ['ROOT_DIR'])
generator_name = os.environ.get('GENERATOR_NAME', 'generate-readme.sh')
excluded = {"README.md", generator_name}
entries = []

for path in sorted(root.rglob('*')):
    if not path.is_file():
        continue
    rel = path.relative_to(root)
    if rel.parts[0] == '.git':
        continue
    if rel.name in excluded:
        continue

    text = path.read_text(errors="ignore")
    lines = text.splitlines()
    if not lines:
        continue

    summary = None
    desc = []
    prefix = None
    in_desc = False

    for raw in lines:
        stripped = raw.lstrip()
        if summary is None:
            if stripped.startswith('# Summary:'):
                summary = stripped.split(':', 1)[1].strip()
                prefix = '#'
                continue
            if stripped.startswith('// Summary:'):
                summary = stripped.split(':', 1)[1].strip()
                prefix = '//'
                continue
        elif not in_desc:
            if stripped.startswith(prefix + ' Description:'):
                in_desc = True
            continue
        else:
            if not stripped:
                break
            if stripped.startswith(prefix):
                desc_line = stripped[len(prefix):].strip()
                desc.append(desc_line)
                continue
            break

    if summary and desc:
        entries.append({
            'path': rel.as_posix(),
            'summary': summary,
            'description': desc,
        })

if not entries:
    raise SystemExit('No script documentation blocks found.')

overview_lines = []
body_lines = []

body_lines.append('# Tutero Scripts')
body_lines.append('')
body_lines.append(f'This README is generated by `{generator_name}`. Run it after changing any script documentation.')
body_lines.append('')
body_lines.append('## Overview')
for entry in entries:
    overview_lines.append(f"- [`{entry['path']}`](./{entry['path']}) — {entry['summary']}")
body_lines.extend(overview_lines)
body_lines.append('')
body_lines.append('## Scripts')

for entry in entries:
    body_lines.append(f"### [`{entry['path']}`](./{entry['path']})")
    body_lines.append('')
    for line in entry['description']:
        body_lines.append(f"{line}  ")
    body_lines.append('')

Path(os.environ['README_PATH']).write_text('\n'.join(body_lines).rstrip() + '\n')
PY

chmod +x generate-readme.sh
